# cloudbuild.yaml all
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sample-app:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sample-app:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/sample-app-green'
      - 'sample-app=gcr.io/$PROJECT_ID/sample-app:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/sample-app-green'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'selector'
      - 'service/sample-app-service'
      - '--selector=app=sample-app-green'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'delete'
      - 'deployment'
      - 'sample-app-blue'

# Specify logs bucket (Cloud Storage bucket for logs)
logsBucket: gs://sample-app-app

images:
  - 'gcr.io/$PROJECT_ID/sample-app:$COMMIT_SHA'
